# Generated by Django 6.0.1 on 2026-02-08 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique reference from source system or CSV', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('sale', 'Sale'), ('refund', 'Refund')], max_length=20)),
                ('description', models.TextField()),
                ('merchant', models.CharField(blank=True, help_text='Vendor or merchant name if applicable', max_length=255, null=True)),
                ('transaction_date', models.DateField(help_text='Actual date the transaction occurred')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the record entered the system')),
                ('is_flagged', models.BooleanField(default=False, help_text='Marked suspicious by rules or admin')),
                ('source', models.CharField(default='csv', help_text='csv, api, manual', max_length=50)),
                ('employee', models.ForeignKey(help_text='Employee who logged or uploaded this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_probability', models.FloatField()),
                ('final_decision', models.CharField(choices=[('approve', 'Approve'), ('review', 'Review')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='transactions.transaction')),
            ],
        ),
    ]
