# Generated by Django 6.0.2 on 2026-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_prediction_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraud_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ml_flag',
            field=models.IntegerField(default=0),
        ),
    ]
