# Generated by Django 6.0.2 on 2026-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fraud_probability_transaction_ml_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
