# Generated by Django 6.0.2 on 2026-02-27 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_add_uploaded_at_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_review_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin when blocking', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
